version: "3"
services:
  web:
    build:
      context: ./miner-web
    ports:
      - "8080:8080"
    restart: always
    networks:
      net-miner:
        ipv4_address: 10.172.17.2

  request:
    build:
      context: ./FuzzyMiner
    ports:
      - "8000:8000"
    volumes:
      - ./FuzzyMiner/media:/usr/share/nginx/FuzzyMiner/media:rw  
    restart: always
    networks:
      net-miner:
        ipv4_address: 10.172.17.3

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./FuzzyMiner/media:/usr/share/nginx/FuzzyMiner/media:ro
    depends_on:
      - web
      - request
    restart: always
    networks:
      net-miner:
        ipv4_address: 10.172.17.4

networks:
  net-miner:
    ipam:
      config:
        - subnet: 10.172.17.0/24
